repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=2048]
  - repo: local
    hooks:
      - id: format
        name: format
        entry: ruff format
        language: python
        types: [python]
        pass_filenames: false
        verbose: true
      - id: check
        name: check
        entry: ruff check
        language: python
        types: [python]
        pass_filenames: false
        verbose: true
      - id: static-typing
        name: static-typing
        entry: mypy src/
        language: python
        types: [python]
        pass_filenames: false
        verbose: true
      - id: test-static-typing
        name: test-static-typing
        entry: mypy test/
        language: python
        types: [python]
        pass_filenames: false
        verbose: true
      - id: test
        name: test
        entry: pytest --cov lenetf9
        language: python
        types: [python]
        pass_filenames: false
        verbose: true
